CasaDoCodigo/Models/ErrorViewModel.cs
using System;

namespace CasaDoCodigo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CasaDoCodigo/Models/ItemPedido.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CasaDoCodigo.Models
{
    public class ItemPedido
    {
        public int Id { get; private set; }

        public Produto Produto { get; private set; }

        public int Quantidade { get; private set; }

        public decimal PrecoUnitario { get; private set; }

        public decimal Subtotal
        {
            get

            {
                return Quantidade * PrecoUnitario;
            }
        }

        public ItemPedido()
        {

        }

        //Encadeamento de construtores com this
        public ItemPedido(int id, Produto produto, int quantidade)
            : this(produto, quantidade)
        {
            this.Id = id;
        }

        //Construtor para ItensPedido-Carrinho
        public ItemPedido(Produto produto, int quantidade)
        {
            this.Produto = produto;
            this.Quantidade = quantidade;
            this.PrecoUnitario = produto.Preco;
        }

    }
}

CasaDoCodigo/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CasaDoCodigo.Models
{
    public class Produto
    {
        /// <summary>
        /// Id do produto
        /// </summary>
        public int Id { get; private set; }

        /// <summary>
        /// Nome do produto
        /// </summary>
        public string Nome { get; private set; }

        /// <summary>
        /// Preço do produto
        /// </summary>
        public decimal Preco { get; private set; }

        public Produto()
        {

        }

        //Encadeamento de construtores com this
        public Produto(int id, string nome, decimal preco)
            : this(nome, preco)
        {
            this.Id = id;
        }

        //Construtor para ItensPedido-Carrinho
        public Produto(string nome, decimal preco)
        {
            this.Nome = nome;
            this.Preco = preco;
        }

    }
}

CasaDoCodigo/Models/ViewModels/CarrinhoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CasaDoCodigo.Models.ViewModels
{
    public class CarrinhoViewModel
    {
        /// <summary>
        /// Itens do pedido
        /// </summary>
        public List<ItemPedido> Itens { get; private set; }

        /// <summary>
        /// Valor total da compra
        /// </summary>
        public decimal Total
        {
            get
            {
                return Itens.Sum(i => i.Subtotal);
            }
        }

        public CarrinhoViewModel(List<ItemPedido> Itens)
        {
            this.Itens = Itens;
        }

    }
}

CasaDoCodigo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CasaDoCodigo.Models;

namespace CasaDoCodigo.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CasaDoCodigo/Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CasaDoCodigo.Models;
using CasaDoCodigo.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CasaDoCodigo.Controllers
{
    public class PedidoController : Controller
    {
        private readonly IDataService _dataService;
        public PedidoController(IDataService dataService)
        {
            this._dataService = dataService;
        }

        public IActionResult Carrossel()
        {
            List<Produto> produtos = _dataService.GetProdutos();
            return View(produtos);
        }

        public IActionResult Carrinho()
        {
            CarrinhoViewModel carrinho = GetCarrinhoViewModel();

            return View(carrinho);
        }

        private CarrinhoViewModel GetCarrinhoViewModel()
        {
            List<Produto> produtos = this._dataService.GetProdutos();//Não passo mais os intens fixos.

            var itensCarrinho = this._dataService.GetItensPedido();//Os itens vem do banco

            CarrinhoViewModel carrinho = new CarrinhoViewModel(itensCarrinho);
            return carrinho;
        }

        public IActionResult Resumo()
        {
            CarrinhoViewModel carrinho = GetCarrinhoViewModel();
            return View(carrinho);
        }
    }
}

CasaDoCodigo/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

CasaDoCodigo/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CasaDoCodigo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

CasaDoCodigo/Views/Pedido/Carrinho.cshtml
@{
    ViewData["Title"] = "Carrinho de Compras";
}

@model CasaDoCodigo.Models.ViewModels.CarrinhoViewModel

<h3>Meu Carrinho</h3>

<div class="panel panel-default">
    <div class="panel-heading">

        <div class="row">
            <div class="col-md-6">
                Item
            </div>
            <div class="col-md-2 text-center">
                Preço Unitário
            </div>
            <div class="col-md-2 text-center">
                Quantidade
            </div>
            <div class="col-md-2">
                <span class="pull-right">SubTotal</span>
            </div>
        </div>

    </div>

    <div class="panel-body">
        @foreach (var item in Model.Itens)
        {
            <div class="row row-center">
                <div class="col-md-3">
                    <img src="~/images/produtos/small_@(item.Id).jpg" />
                </div>
                <div class="col-md-3">@item.Produto.Nome</div>
                <div class="col-md-2 text-center">R$ @item.PrecoUnitario</div>
                <div class="col-md-2 text-center">@item.Quantidade</div>
                <div class="col-md-2">
                    <span class="pull-right">
                        R$ @item.Subtotal
                    </span>
                </div>
            </div>
        }
    </div>

    <div class="panel-footer">

        <div class="row">
            <div class="col-md-10">
                <span>Total: @Model.Itens.Count() @(Model.Itens.Count() < 2 ? "Item" : "Itens")</span>
            </div>
            <div class="col-md-2">
                <span class="pull-right">
                    Total: R$ @Model.Total
                </span>
            </div>
        </div>

    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <a asp-action="resumo" class="btn btn-success pull-right">Finalizar Pedido</a>
        @*@Html.ActionLink("Finalizar Pedido", "resumo", "pedido", null, new { @class = "btn btn-success pull-right" })*@
        @*<a href="/pedido/resumo" class="btn btn-success pull-right">Finalizar Pedido</a>*@
    </div>
</div>

CasaDoCodigo/Views/Pedido/Carrossel.cshtml
@{
    ViewData["Title"] = "Carrossel";
}

@model List<Produto>

<h3>Catálogo</h3>

<div id="my-carousel" class="carousel slide" data-ride="carousel">

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        @{
            const int TAMANHO_PAGINA = 4;
            int numPaginas =(int)Math.Ceiling((double)Model.Count() / TAMANHO_PAGINA);
        }

        @for (int pagina = 0; pagina < numPaginas; pagina++)
        {
            <div class="item @(pagina == 0 ? "active":"")">
                <div class="row">
                    @{ 
                        var produtoPagina = Model
                            .Skip(TAMANHO_PAGINA * pagina)
                            .Take(TAMANHO_PAGINA);
                    }
                    @foreach (Produto produto in produtoPagina)
                    {
                        <div class="col-md-3">
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    <img src="~/images/produtos/large_@(produto.Id).jpg" />
                                </div>
                                <div class="panel-footer">
                                    <div>@(produto.Nome)</div>
                                    <div>R$ @(produto.Preco)</div>
                                    <div class="text-center">
                                        @Html.ActionLink("Adicionar", "carrinho", "pedido")
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>

        }

    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#my-carousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#my-carousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

CasaDoCodigo/Views/Pedido/Resumo.cshtml
@{
    ViewData["Title"] = "Resumo";
}
@model CasaDoCodigo.Models.ViewModels.CarrinhoViewModel

<h3>Resumo do Pedido</h3>

<div class="panel panel-default">
    <div class="panel-body">
        <div class="row">
            <div class="col-md-12">
                <h3>Nº do Pedido: 123456789</h3>
            </div>
        </div>

        <hr />

        <div class="row">
            <div class="col-md-3">
                <h3>Seus Dados</h3>
                <div>(11) 80660559</div>
            </div>
            <div class="col-md-3">
                SophiaOliveira@com.br
            </div>
            <div class="col-md-6">
                <h3>Endereço de Entrega</h3>
                <div>Rua Tapaxanas 138</div>
            </div>
        </div>

        <hr />

        <div class="row">
            <div class="col-md-10">
                <h3>Item</h3>                
            </div>
            <div class="col-md-2">
                <h3>Quantidade</h3>              
            </div>
        </div>

        @foreach (var item in Model.Itens)
        {
            <div class="row">
                <div class="col-md-10">                   
                    <div>@item.Produto.Nome</div>
                </div>
                <div class="col-md-2">                  
                    <div class="pull-right">@item.Quantidade</div>
                </div>
            </div>
        }


    </div>
</div>

CasaDoCodigo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Casa do Código</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Pedido" asp-action="Carrossel" class="navbar-brand"></a>
            </div>
            <div class="navbar-collapse collapse"></div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - Imagine Software</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>